MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace EjemploControllers.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        [Display(Name = "Nombre de usuario")]
        [Required]
        [MaxLength(250)]
        public string Nombre { get; set; }

        [Display(Name = "Dirección de email")]
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "Contraseña")]
        [MinLength(6)]
        [MaxLength(28)]
        public string Password { get; set; }
    }
}

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Controllers/HomeController.cs
using EjemploControllers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjemploControllers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View(new Usuario
            {
                Nombre = "Diego Bersano"
            });
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Controllers/UsuariosController.cs
using EjemploControllers.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EjemploControllers.Controllers
{
    public class UsuariosController : Controller
    {
        private static IList<Usuario> usuarios = new List<Usuario>();

        public ActionResult Index()
        {
            return View(usuarios);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Usuario model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Id = usuarios.Count() + 1;
            usuarios.Add(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var usuario = usuarios.Where(x => x.Id == id).Single();

            return View(usuario);
        }

        [HttpPost]
        public ActionResult Edit(Usuario model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var usuario = usuarios.Where(x => x.Id == model.Id).Single();
            usuario.Nombre = model.Nombre;
            usuario.Email = model.Email;
            usuario.Password = model.Password;

            return RedirectToAction("Index");
        }
    }
}

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Home/Index.cshtml
@using EjemploControllers.Models
@model Usuario

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

@Html.Partial("_Usuario", Model.Nombre)

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Shared/_Usuario.cshtml
@model string

<style>
    .rojo {
        color: red;
    }
</style>

<h3>
    Invocada por
</h3>
<ul>
    @foreach (var item in Model)
    {
        if (item != ' ')
        {
            var esVocal = item == 'a'
                || item == 'e'
                || item == 'i'
                || item == 'o'
                || item == 'u';

            <li class="@(esVocal ? "rojo" : "")">@item</li>
        }
    }
</ul>

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Usuarios/Create.cshtml
@using EjemploControllers.Models
@model Usuario

<h1>Crear usuario</h1>
@using (Html.BeginForm("Create", "Usuarios", FormMethod.Post,
        new { @class = "", role = "form" }))
{
    @Html.ValidationSummary()

    @Html.Partial("_Form", Model)
}

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Usuarios/Edit.cshtml
@using EjemploControllers.Models
@model Usuario

<h1>Editar usuario</h1>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    @Html.HiddenFor(x => x.Id)
    @Html.Partial("_Form", Model)
}

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Usuarios/Index.cshtml
@using EjemploControllers.Models
@model IList<Usuario>

<h1>Usuarios</h1>
@Html.ActionLink("Crear", "Create")

<ul>
    @foreach (var usuario in Model)
    {
        <li>
            @usuario.Nombre
            @Html.ActionLink("Editar", "Edit", new { id = usuario.Id })
        </li>

    }
</ul>

MVC/MVC/Controllers/EjemploControllers/EjemploControllers/Views/Usuarios/_Form.cshtml
@using EjemploControllers.Models
@model Usuario

<div class="form-group">
    @Html.LabelFor(x => x.Nombre)
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Email)
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Email)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Password)
    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Password)
</div>

<button type="submit">Enviar</button>