MVC/MVC/Controllers/CategoriaController.cs
using Contract;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Contract.IService;

namespace MVC.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly IService categoryService;
        public CategoriaController(IService categoryService)
        {
            this.categoryService = categoryService;
        }

        public ActionResult Index()
        {
            var categories = categoryService.Getcategory();

            IList<CategoriaModel> categories1 = new List<CategoriaModel>();

            foreach (var cat in categories)
            {
                var creada = new CategoriaModel { Id = cat.Id, Active = cat.Active, Description = cat.Description, Name = cat.Name };
                categories1.Add(creada);
            }

            return View(categories1);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (categoryService.DeleteCategory(id))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(CategoriaModel model)
        {
            if (ModelState.IsValid)
            {
                return View(model);
            }
            var category = new Categoria { Id = model.Id, Active = model.Active, Description = model.Description, Name = model.Name };
            categoryService.SaveCategory(category);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var category = categoryService.SearchCategory(id);

            return View(new CategoriaModel { Id = category.Id, Name = category.Name, Active = category.Active, Description = category.Description });
        }

        [HttpPost]
        public ActionResult Edit(CategoriaModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var category = new Categoria { Id = model.Id, Active = model.Active, Description = model.Description, Name = model.Name };

            categoryService.EditCategory(category);

            return RedirectToAction("Index");
        }
    }
}

MVC/MVC/Controllers/NotasController.cs
using Contract;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class NotasController : Controller
    {
        private readonly IServicioNotas notasService;

        public NotasController(IServicioNotas notasService)
        {
            this.notasService = notasService;
        }

        public ActionResult Index()
        {
            var notas = notasService.GetNews();

            IList<NotaModel> notas1 = new List<NotaModel>();

            foreach (var cat in notas)
            {
                var creada = new NotaModel { Id = cat.Id, Active = cat.Active, Descripcion = cat.Descripcion, Titulo = cat.Titulo };
                notas1.Add(creada);
            }

            return View(notas1);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NotaModel model)
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(int id)
        {
            return RedirectToAction("Index");
        }
    }
}

MVC/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Login.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Crear", "Create", "Categoria")</li>
                    <li>@Html.ActionLink("Editar", "Edit", "Categoria")</li>
                    <li>@Html.ActionLink("Tabla", "Index", "Categoria")</li>
                    <li>@Html.ActionLink("Noticias", "Index", "Notas")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET - Lautaro Muller</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>